In [2]:
import numpy as np
import trfp
import scipy.optimize

In [3]:
type(np.arange(10)[0])

numpy.int64

In [4]:
print(len(trfp.STATION_PROBE_ID))
#trfp.FP4_X
#trfp.FP4_X_ST37_ST39
#trfp.FP4_X_ST41


72


In [5]:
#Drop probe 0 expectations:


In [6]:
def __multipole(order, skew, strength, x_pos, y_pos):
    """Returns the magnitude of a B-field given multipole parameters
    and position.
    """
    # Takes a multipole strength A normalized to 4.5 cm
    r_pos = np.sqrt(x_pos**2 + y_pos**2)
    theta = np.arctan2(y_pos, x_pos)
    if skew == 0:
        b_magnitude = strength * (r_pos/4.5)**order * np.cos(order*theta)
    if skew == 1:
        b_magnitude = strength * (r_pos/4.5)**order * np.sin(order*theta)
    return b_magnitude

# Probe Geometry.
class Geometry:
    def __init__(self, x, y, p):
        self.xpos = x
        self.ypos = y
        self.probes = p.astype('int')
        if len(self.xpos) != len(self.ypos):
            print("In Geometry length of xpos and ypos are not equal")
        elif len(self.ypos) != len(self.probes):
            print("In Geometry length of probes and ypos are not equal")
    def IsReduced(self):
        isReduced = True
        for i in self.probes:
            if i == 0:
                isReduced = False
        return isReduced
#__ _ _ will not import a function.
#From module import * will not import __function or _ at end ... like geometry_

In [7]:
test = np.arange(10)
print(test)
print(test[:10])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
def DropPos(geom):
    badProbes = np.array([])
    for i in range(len(geom.probes)):
        if geom.probes[i] == 0:
            badProbes = np.append(badProbes, i)
    badProbes = badProbes.astype(int)
    X = geom.xpos.copy()
    Y = geom.ypos.copy()
    px_new = np.delete(X, badProbes) # Only the x pos of working probes stay
    py_new = np.delete(Y, badProbes) # Same for y
    PROBES_NEW = np.delete(geom.probes, badProbes) #Now this is an array of 1s.
    reducedGeometry = Geometry(px_new, py_new, PROBES_NEW)
    return reducedGeometry, badProbes

def Theta(Multipole, geom, badProbes, mult_order, mult_skew, tpMomentCap, fpMomentCap):    
    #"If then" for truncating moments, can recover all moments from dropping 1 trfp 
    
    #if not geom.IsReduced():
    #    print("The geometry given has non-working probes")
    #    return
    
    lenOrigProbes = len(geom.probes) + len(badProbes)
    
    if (lenOrigProbes > 6):
        momentCap = tpMomentCap
    else:
        momentCap = fpMomentCap
    
    if (len(geom.probes) < momentCap):
        print("Moment cap is higher for the number of functional probes")
    
    _MULTS_FP_N = np.array([__multipole(mult_order[i], mult_skew[i], 1, geom.xpos, geom.ypos)\
                                for i in range(momentCap)])
        
    _MULTS_FP_N[np.abs(_MULTS_FP_N) < 1.0e-9] = 0
    
    INV_MULT = np.linalg.pinv(np.transpose(_MULTS_FP_N))
    INV_MULT[np.abs(INV_MULT) < 1.0e-9] = 0
    
    I = np.dot(INV_MULT,np.transpose(_MULTS_FP_N))
    I[np.abs(I) < 1.0e-9] =0
    #print(I)
    #Add the columns of 0
    inv_mult = np.zeros((len(INV_MULT), lenOrigProbes))
    j = 0
    if len(badProbes) > 0:
        badProbesCopy = badProbes.copy()
        for i in range(lenOrigProbes):
            if i != badProbesCopy[0]:
                inv_mult[:,i] = INV_MULT[:,j]
                j+=1
            elif (i == badProbesCopy[0]) and (len(badProbesCopy) > 1):
                badProbesCopy = np.delete(badProbesCopy, 0)
                  
        #Add rows at the end, only the first moments can be calculated
        for i in range(lenOrigProbes - momentCap):
            inv_mult = np.concatenate((inv_mult, np.zeros((1,lenOrigProbes))))
        return(inv_mult)
    else:
        for i in range(lenOrigProbes - momentCap):
            INV_MULT = np.concatenate((INV_MULT, np.zeros((1,lenOrigProbes))))
            
        return(INV_MULT)

    
def ProbeDrops(geom, tpMomentCap = 14, fpMomentCap = 5):
    reducedGeometry, badProbes = DropPos(geom)# Return another geom
    
    _MULTIPOLE_ORDER = [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 7]
    _MULTIPOLE_SKEW = [0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1]
    if len(geom.probes) < len(_MULTIPOLE_ORDER):
        _MULTIPOLE_ORDER = _MULTIPOLE_ORDER[:len(geom.probes)]
        _MULTIPOLE_SKEW = _MULTIPOLE_SKEW[:len(geom.probes)]

    return Theta(__multipole, reducedGeometry, badProbes, _MULTIPOLE_ORDER, _MULTIPOLE_SKEW, tpMomentCap, fpMomentCap)

In [15]:
geom = Geometry(trfp.TR_X, trfp.TR_Y, np.zeros(17)+1)
for i in range(14):
    print(ProbeDrops(geom, tpMomentCap=i+1, fpMomentCap=5)[0])
    print('\n')

[0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353]


[0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353]


[0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353]


[0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353]


[0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353
 0.05882353 0.05882353 0.05882353 0.05882353 0.05882353]


[0.05882353 0.05882353 0.05882353 0

In [38]:
probes = np.zeros(6) + 1
probes[0] = 0
probes[3] = 0
fpGeom = Geometry(trfp.FP6_X, trfp.FP6_Y, probes)
fpTheta = ProbeDrops(fpGeom, fpMomentCap = 4)
#print("Dropped probe 0, [m1,m4] \n")
print(fpTheta)

Dropped probe 0, [m1,m4] 

[[ 0.          0.5         0.          0.          0.5         0.        ]
 [ 0.         -0.75        0.75        0.         -0.75        0.75      ]
 [ 0.          0.29220779  0.          0.         -0.29220779  0.        ]
 [ 0.         -0.21915584  0.21915584  0.          0.21915584 -0.21915584]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]]


In [34]:
probes = np.zeros(6) + 1
#probes[0] = 0
probes[1] = 0
fpGeom = Geometry(trfp.FP6_X, trfp.FP6_Y, probes)
fpTheta = ProbeDrops(fpGeom, fpMomentCap = 5)
print("Dropped probe 0, [m1,m5] \n")
print(fpTheta)

Dropped probe 0, [m1,m5] 

[[ 0.25        0.          0.25        3.04388889 -5.58777778  3.04388889]
 [-0.375       0.          0.375      -0.375       0.          0.375     ]
 [ 0.1461039   0.          0.1461039  -0.1461039   0.         -0.1461039 ]
 [-0.10957792  0.          0.10957792  0.10957792  0.         -0.10957792]
 [ 0.          0.          0.          1.125      -2.25        1.125     ]
 [ 0.          0.          0.          0.          0.          0.        ]]


In [ ]:
print(np.matmul(trfp.J_4_PROBE[:4, :4], trfp.THETA_FP_4))

In [ ]:
print(trfp.J_4_PROBE)
print(trfp.THETA_FP_4)

In [ ]:
print(trfp.THETA_TR)

In [ ]:
J_6_PROBE6x6 = np.array([[1.0, 0.0, 0.0, 0.0, 2.631605, 0.0],
                         [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
                         [0.0, 0.0, 1.0, 0.0, 0.0, -0.339835],
                         [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
                         [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
                         [0.0, 0.0, 0.0, 0.0, 0.0, -0.166667]])

J_6_PROBE = np.array([[1.0, 0.0, 0.0, 0.0, 2.631605],
                      [0.0, 1.0, 0.0, 0.0, 0.0],
                      [0.0, 0.0, 1.0, 0.0, 0.0],
                      [0.0, 0.0, 0.0, 1.0, 0.0],
                      [0.0, 0.0, 0.0, 0.0, 1.0]])

J_6_PROBE_OFFSET = np.array([[1.0, 0.222222, 0.0, 0.0, 2.680987],
                             [0.0, 1.0, 0.0, 0.0, 0.444444],
                             [0.0, 0.0, 1.0, 0.444444, 0.0],
                             [0.0, 0.0, 0.0, 1.0, 0.0],
                             [0.0, 0.0, 0.0, 0.0, 1.0]])

J_4_PROBE = np.array([[1.0, 0.0, 0.0, 0.0, 2.927901],
                      [0.0, 1.0, 0.0, 0.0, -0.666667],
                      [0.0, 0.0, 1.0, -0.666667, 0.0],
                      [0.0, 0.0, 0.0, 1.0, 0.0],
                      [0.0, 0.0, 0.0, 0.0, 1.0]])

J_4_PROBE_ST41 = np.array([[1.0, 0.0, 0.0, 0.0, 2.927901],
                           [0.0, 1.0, 0.0, 0.0, 0.0],
                           [0.0, -0.194805, 1.0, 0.0, 0.0],
                           [0.0, 0.0, 0.0, 1.0, -0.194805],
                           [0.0, 0.0, 0.0, 0.0, 1.0]])

J_4_PROBE_ST37_ST39 = np.array([[1.0, 0.0, 0.0, 0.0, 2.927901],
                                [0.0, 1.0, 0.0, 0.0, 0.0], 
                                [0.0, -0.194805, 1.0, 0.0, 0.0], 
                                [0.0, 0.0, 0.0, 1.0, -0.194805], 
                                [0.0, 0.0, 0.0, 0.0, 1.0]])

In [ ]:
THETA_FP_6 = np.array([np.array([1, 1, 1, 1, 1, 1])/6.,  # dipole
                       np.array([1, 0, -1, 1, 0, -1])/-12.*4.5,  # n quad
                       np.array([1, 1, 1, -1, -1, -1])/46.2*4.5,  # s quad
                       np.array([1, 0, -1, -1, 0, 1])/-92.4/2*4.5**2,  # s sext
                       np.array([1, -2, 1, 1, -2, 1])/18./2*4.5**2,  # n sext
                       np.array([1, -2, 1, -1, 2, -1])/-138.6*4.5**3]  # NOT oct, no idea what this is
                     )

THETA_FP_4 = np.array([np.array([1, 0, 1, 0])/2.,  # dipole
                       np.array([1, -1, 1, -1])/-6.*4.5,  # n quad
                       np.array([1, 1, -1, -1])/30.8*4.5,  # s quad
                       np.array([1, -1, -1, 1])/-46.2/2*4.5**2]  # sext
                     )

# four probe stations in the garage (stations 37, 39, 41) have a different arrangement of probes
# STATION 37, 39
# TM, TO, BI, BM
THETA_FP_4_ST37_ST39 = np.array([np.array([1, 0, 0, 1])/2.,  #dipole
                                 np.array([-1, 1, -1, 1])/6.*4.5,  # n quad
                                 np.array([1, 1, -1, -1])/30.8*4.5,  # s quad
                                 np.array([-1, 1, 1, -1])/46.2/2*4.5**2]  # sext?
                               )
# STATION 41
# TO, TM, BI, BM
THETA_FP_4_ST41 = np.array([np.array([0, 1, 0, 1])/2.,  #dipole
                            np.array([1, -1, -1, 1])/6.*4.5,  # n quad
                            np.array([1, 1, -1, -1])/30.8*4.5,  # s quad
                            np.array([1, -1, 1, -1])/46.2/2*4.5**2]  # sext?
                          )

In [ ]:
#Checking what each probe would read given a moment of magnitude 1
_MULTIPOLE_ORDER = [0, 1, 1, 2, 2, 3]
_MULTIPOLE_SKEW = [0, 0, 1, 1, 0, 1]

#_MULTIPOLE_ORDER = [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 7]
#_MULTIPOLE_SKEW = [0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1]

_MULTS_FP_N = np.array([__multipole(_MULTIPOLE_ORDER[i], _MULTIPOLE_SKEW[i], 1, FP6_X, FP6_Y) for i in range(len(_MULTIPOLE_ORDER) - len(drops))])
_MULTS_FP_N[np.abs(_MULTS_FP_N) < 1.0e-9] = 0
#print(_MULTS_FP_N)

THETA_FPN = np.linalg.pinv(np.transpose(_MULTS_FP_N))
THETA_FPN[np.abs(THETA_FPN) < 1.0e-9] = 0
print(THETA_FPN)
#print(THETA_FP_6)

The above code works for 6 working fp. Below will be testing for 4 probes

In [ ]:
#### For some reason this changes when more multipoles are used. I am assuming it has to do with m6 not bing linearly indep.
_MULTIPOLE_ORDER = [0, 1, 1, 2, 2, 3]
_MULTIPOLE_SKEW = [0, 0, 1, 1, 0, 0]
_MULTS_FP6 = np.array([__multipole(_MULTIPOLE_ORDER[i], _MULTIPOLE_SKEW[i], 1, FP6_X, FP6_Y) for i in range(len(_MULTIPOLE_ORDER))])
_MULTS_FP6[np.abs(_MULTS_FP6) < 1.0e-9] = 0

THETA_FP6 = np.linalg.pinv(np.transpose(_MULTS_FP6))
THETA_FP6[np.abs(THETA_FP6) < 1.0e-9] = 0
print(THETA_FP6)

In [ ]:
######### Below is an attempt to create a station with 4 probes

In [ ]:
PROBES = [0,1,1,0,1,1] #1 means the probe is working properly, 0, it is dropped or does not exist.
drops = np.array([])
for i in range(len(PROBES)):
    if not PROBES[i]:
        drops = np.append(drops, i)
drops = drops.astype(int)


FP6_X_NEW = np.delete(FP6_X, drops)  # now only the x pos of working probes are stored
FP6_Y_NEW = np.delete(FP6_Y, drops)  # same with y pos
PROBES_NEW = np.delete(PROBES, drops)# array of 1s of length of the number of working probes

In [ ]:
_MULTIPOLE_ORDER = [0, 1, 1, 2, 2, 3]
_MULTIPOLE_SKEW = [0, 0, 1, 1, 0, 1]

_MULTS_FP_N = np.array([__multipole(_MULTIPOLE_ORDER[i], _MULTIPOLE_SKEW[i], 1, FP6_X_NEW, FP6_Y_NEW) for i in range(len(_MULTIPOLE_ORDER) - len(drops))])
_MULTS_FP_N[np.abs(_MULTS_FP_N) < 1.0e-9] = 0

INV_MULT = np.linalg.pinv(np.transpose(_MULTS_FP_N))
INV_MULT[np.abs(INV_MULT) < 1.0e-9] = 0

#Add the columns of 0s
inv_mult = np.zeros((len(INV_MULT), len(PROBES)))
j = 0
for i in range(len(PROBES)):
    if PROBES[i] == 1:
        inv_mult[:,i] = INV_MULT[:,j]
        j+=1
#Add rows
for i in range(len(PROBES) - len(PROBES_NEW)):
    inv_mult = np.concatenate((inv_mult, np.zeros((1,len(PROBES)))))

THETA = np.dot(np.linalg.pinv(J_6_PROBE6x6), inv_mult)
THETA[np.abs(THETA) < 1.0e-9] = 0
THETA = THETA[:len(PROBES_NEW)]
T = np.zeros((len(PROBES_NEW),len(PROBES_NEW)))
j = 0
for i in range(len(PROBES)):
    if(np.sum(np.abs(THETA[:,i])))> 1e-8:
        T[:,j] = THETA[:,i]
        j+=1
THETA = T
print("Calculated Theta for 4 fp stattion")
print(THETA)
print("############")
print("Hard Coded theta for 4 fp station")
print(np.array([np.array([1, 0, 1, 0])/2.,  # dipole
                       np.array([1, -1, 1, -1])/-6.*4.5,  # n quad
                       np.array([1, 1, -1, -1])/30.8*4.5,  # s quad
                       np.array([1, -1, -1, 1])/-46.2/2*4.5**2]  # sext
                     )
)

In [ ]:
####### Now trolley

In [ ]:
PROBES = np.zeros(17) + 1 #1 means the probe is working properly, 0, it is dropped or does not exist.
PROBES = PROBES.astype('int')
PROBES[8] = 0
print(PROBES)
drops = np.array([]) #This is meant to be empty, will be filled to know what probes to drop
for i in range(len(PROBES)):
    if not PROBES[i]:
        drops = np.append(drops, i)
drops = drops.astype(int)

X = trfp.TR_X.copy()
Y = trfp.TR_Y.copy()

TR_X_NEW = np.delete(X, drops)  # now only the x pos of working probes are stored
TR_Y_NEW = np.delete(Y, drops)  # same with y pos
PROBES_NEW = np.delete(PROBES, drops)# array of 1s of length of the number of working probes

In [ ]:
_MULTIPOLE_ORDER = [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 7]
_MULTIPOLE_SKEW = [0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1]
# Skew 14 pole is unmeasurable probes are on nodes.
# 4  is 10 pole, anything above this is unreliable. Uncertainty on cal. coeff. --> prop. uncertainty...
# on cal. becomes too large

if len(drops) == 0:
    _MULTS_TR_N = np.array([__multipole(_MULTIPOLE_ORDER[i], _MULTIPOLE_SKEW[i], 1, TR_X_NEW, TR_Y_NEW) for i in range(len(_MULTIPOLE_ORDER))])

else: #This else must be corrected for trolley drops instead of fp
    _MULTS_TR_N = np.array([__multipole(_MULTIPOLE_ORDER[i], _MULTIPOLE_SKEW[i], 1, TR_X_NEW, TR_Y_NEW) for i in range(len(_MULTIPOLE_ORDER) - len(drops) + 1)])

_MULTS_TR_N[np.abs(_MULTS_TR_N) < 1.0e-9] = 0 


INV_MULT = np.linalg.pinv(np.transpose(_MULTS_TR_N))
INV_MULT[np.abs(INV_MULT) < 1.0e-9] = 0
#Add the columns of 0s
inv_mult = np.zeros((len(INV_MULT), len(PROBES)))
j = 0
for i in range(len(PROBES)):
    if PROBES[i] == 1:
        inv_mult[:,i] = INV_MULT[:,j]
        j+=1
for i in range(len(PROBES) - len(PROBES_NEW)):
    inv_mult = np.concatenate((inv_mult, np.zeros((1,len(PROBES)))))
    
print(inv_mult)